server:
  port: 8092

spring:
  application:
    name: consumer_employee
  jpa:
    properties:
      hibernate.default_schema: consumer_employee
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/integrations
    username: postgres
    password: postgres

#flyway:
#  driverClassName: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/integrations
#  username: postgres
#  password: postgres
  default-schema: consumer_employee
aws:
  region: us-east-1
  access-key:  ${AWS_KEY}
  secret-key: ${AWS_SECRET_KEY}   
queue:
  employee:
    created:
      name: EMPLOYEE_CREATED_QUEUE
      pool-size: 1-3
    removed:
      name: EMPLOYEE_REMOVED_QUEUE
      pool-size: 1-3
